server:
  port: 8081
  ssl:
    enabled: false

bot:
  name: SerjMaksTestBot
  token: 5245134931:AAGNXzcRTkJc4shwrK27Fp4CgWoDJPBlBOU
  url: https://d3c2-109-197-204-107.ngrok-free.app

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

#logging:
#   file:
#     name: ./logs/dispatcher.log
#   level:
#     root: DEBUG
#     org.bot.priceparser: DEBUG
#     org.springframework: DEBUG
