server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass

  jpa:
    generate-ddl: true

#logging:
#   file:
#     name: ./logs/node.log
#   level:
#     root: DEBUG
#     org.bot.priceparser: DEBUG
#     org.springframework: DEBUG
